### ISSUE TITLE
DiscordAcePerms-master: Deferring connection...

### ISSUE THREAD

**Issue by TheKidCottons** [JaredScar/DiscordAcePerms#4] opened 2022-01-08 17:48 UTC
Whenever I try and connect to the server, it gets stuck on 'DiscordAcePerms-master: Deferring connection...' Do you know why this is happening?

**Comment by OfficerBozza** [comment] 2022-01-17 08:11
Having same issue.

**Comment by OfficerBozza** [comment] 2022-01-17 11:06
#5 Managed to fix by updating __resource.lua to the newer fxmanifest.lua.

**Comment by JaredScar** [comment] 2022-01-17 14:54
Updating the `__resource.lua` should not fix this issue. That issue is caused by a configuration issue. In other words, you made a mistake in the configuration file and need to fix it in order for this script to work. @TheKidCottons I am closing this because this is not a real issue, but on fault of your own.

**Closed by JaredScar** 2022-01-17 14:54 UTC
